config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "import_files#index"

  resources :import_files
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/import_file.rb
class ImportFile < ApplicationRecord
  has_one_attached :file

  validates :file, presence: true

  has_many :orders, dependent: :destroy
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  validates :name, :address, presence: true

  has_many :orders, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  validates :item_description, :item_price, presence: true

  belongs_to :import_file, optional: true
  belongs_to :purchaser
  belongs_to :merchant
end

app/models/purchaser.rb
class Purchaser < ApplicationRecord
  validates :name, :purchase_count, presence: true

  has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/import_files_controller.rb
class ImportFilesController < ApplicationController
  before_action :set_import_file, only: %i[show destroy]
  after_action :import_orders, only: %i[create]

  def index
    @import_files = ImportFile.all
  end

  def show; end

  def new
    @import_file = ImportFile.new
  end

  def create
    @import_file = ImportFile.new(import_file_params)

    if @import_file.save
      redirect_to import_file_url(@import_file), notice: "Import file was successfully created."

    else
      render :new, status: :unprocessable_entity, notice: "Import file was not created."
    end
  end

  def destroy
    @import_file.destroy

    redirect_to import_files_url, notice: "Import file was successfully destroyed."
  end

  private

  def set_import_file
    @import_file = ImportFile.find(params[:id])
  end

  def import_file_params
    params.require(:import_file).permit(:file)
  end

  def import_orders
    ImportDataService.call(@import_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def import_title(import)
    "Arquivo importado em (#{import.created_at.strftime('%d/%m/%Y - %H:%M:%S')})"
  end

  def import_total_amount(import_files)
    return "R$0,00" if import_files.blank?

    number_to_currency(ImportFile.all.sum(:total_amount), unit: "R$", separator: ",", delimiter: ".")
  end

  def import_last_import_amount(import_file)
    return "R$0,00" unless import_file

    number_to_currency(import_file.total_amount, unit: "R$", separator: ",", delimiter: ".")
  end

  def format_import_item_price(item_price)
    number_to_currency(item_price, unit: "R$", separator: ",", delimiter: ".")
  end
end

app/views/import_files/_form.html.erb
<%= form_with(model: import_file) do |form| %>
  <% if import_file.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(import_file.errors.count, "error") %> prohibited this import_file from being saved:</h2>

      <ul>
        <% import_file.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :file, style: "display: block", for: "formFile", class: "form-label" %>
    <%= form.file_field :file, class:"form-control form-control", id:"formFile" %>
  </div>

  <div class="text-end mt-5">
    <%= form.submit "Salvar", class: "btn btn-success" %>
  </div>
<% end %>

app/views/import_files/index.html.erb
<h1>Importações</h1>

<div class="text-end mt-3 mb-3">
    <%= link_to 'Nova Importação', new_import_file_path, class: "btn btn-primary" %>
</div>

<section>
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="row mt-3 mb-3">
            <div class="col-6">
              <h4 class="text-center">Total de vendas</h4>
              <h5 class="text-center">
                <%= import_total_amount(@import_files) %>
              </h5>
            </div>
            <div class="col-6">
              <h4 class="text-center">Última Importação</h4>
              <h5 class="text-center">
                <%= import_last_import_amount(@import_files.last) %>
              </h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div id="import-list mt-3">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>Descrição</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @import_files.each do |file| %>
            <tr>
              <td><%= file.id %></td>
              <td><%= import_title(file) %></td>
              <td>
                <%= link_to import_file_path(file), class: "btn btn-success" do %>
                  <span>
                    <i class="bi bi-search"></i>
                  </span>
                <%end%>
              </td>
              <td>
                <%= link_to import_file_path(file), method: :delete, class: "btn btn-danger" do %>
                  <span>
                    <i class="bi bi-trash"></i>
                  </span>
                <%end%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</section>

app/views/import_files/new.html.erb
<h3>Importação</h3>

<%= render "form", import_file: @import_file %>

<br>

<div>
  <%= link_to "Voltar", import_files_path %>
</div>

app/views/import_files/show.html.erb
<div class="text-start mt-3 mb-3">
  <%= link_to "Voltar", import_files_path, class: "btn-success" %>
</div>

<div id="import-list">
    <table class="table table-striped">
      <thead>
        <tr>
            <th>Comprador</th>
            <th>Item Descrição</th>
            <th>Preço</th>
            <th>Fornecedor</th>
            <th>Endereço Fornecedor</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @import_file.orders.each do |order| %>
          <tr>
            <td><%= order.purchaser.name %></td>
            <td><%= order.item_description %></td>
            <td><%= format_import_item_price(order.item_price) %></td>
            <td><%= order.merchant.name %></td>
            <td><%= order.merchant.address %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NuuvemChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-8 mt-5">
          <% if notice %>
            <p style="color: green"><%= notice %></p>
          <% end %>
          <%= yield %>
        </div>
      </div>
  </body>
</html>